springfoxdocumentation:
  swagger:
    v2:
      path: /api-docs
      
server:
  port: ${PETSTOREPETSERVICE_SERVER_PORT:8080}
  
spring:
  application:
    name: petstorepetservice
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: ${springboot-datasource-url}
    username: ${springboot-datasource-username}
    password: ${springboot-datasource-pass}
  cloud.azure:
      keyvault:
        secret:
          property-source-enabled: true
          property-sources[0]:
            endpoint: https://petapp-keyvault.vault.azure.net/

  sql:
    init:
      mode: always
#      schema-locations: classpath:schema.sql
#      data-locations: classpath:data.sql
#      platform: postgresql
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create
    show_sql: true
logging:
  level:
#    com.microsoft.azure.keyvault: DEBUG
    org.springframework.cloud.azure: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"       
  trace:
    http:
      enabled: true 
  endpoint:
    httptrace:
      enabled: true
    
